version: '3'
services:
  web:
    restart: always
    env_file:
      - .env
    build: 
      context: .
      dockerfile: docker/prod.Dockerfile
    volumes:
      - ./:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - 8000:8000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  static_volume:
  media_volume: