version: '3'
services:
  web:
    image: 794672242597.dkr.ecr.us-east-1.amazonaws.com/django-ec2:web
    restart: always
    env_file:
      - .env
    build: 
      context: .
      dockerfile: docker/prod.Dockerfile
    volumes:
      - ./:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - 8000:8000
  nginx:
    image: 794672242597.dkr.ecr.us-east-1.amazonaws.com/django-ec2:nginx
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  static_volume:
  media_volume: