version: '3'
services:
  postgres:
    image: postgres:13.7
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 1s
      retries: 5
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_USERNAME
    build: 
      context: .
      dockerfile: docker/local.Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        ./manage.py migrate
        ./manage.py createsuperuser --noinput
        ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy