name: Django application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .env file
        run: |
          mv .env.example .env
      - name: Build docker
        run: docker compose build
      - name: Run isort
        run: docker compose run web isort src/ --check
      - name: Run black
        run: docker compose run web black src/ --check
      - name: Run flake8
        run: docker compose run web flake8
      - name: Run tests
        run: docker compose run web python manage.py test
